# Generated by Django 4.0.2 on 2024-08-17 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.RemoveField(
            model_name='search',
            name='keywords',
        ),
        migrations.AddField(
            model_name='search',
            name='keywords',
            field=models.ManyToManyField(through='search.SearchKeyword', to='search.Keyword'),
        ),
        migrations.AddField(
            model_name='searchkeyword',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.keyword'),
        ),
        migrations.AddField(
            model_name='searchkeyword',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.search'),
        ),
        migrations.AddIndex(
            model_name='searchkeyword',
            index=models.Index(fields=['search', 'keyword'], name='search_sear_search__20d349_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='searchkeyword',
            unique_together={('search', 'keyword')},
        ),
    ]
