# Generated by Django 4.0.2 on 2024-08-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_searchkeyword_alter_keyword_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchkeyword',
            old_name='value',
            new_name='search_count',
        ),
    ]
