# Generated by Django 4.0.2 on 2024-08-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_rename_value_searchkeyword_search_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchkeyword',
            old_name='search_count',
            new_name='value',
        ),
    ]
