# Generated by Django 4.0.2 on 2024-08-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_rename_search_count_searchkeyword_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(db_index=True, max_length=255)),
                ('search_query_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='searchkeyword',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='searchkeyword',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='searchkeyword',
            name='search',
        ),
        migrations.RenameField(
            model_name='keyword',
            old_name='search_count',
            new_name='keyword_search_count',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='name',
        ),
        migrations.AddField(
            model_name='keyword',
            name='keyword_name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='stemmed_keyword_name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Search',
        ),
        migrations.DeleteModel(
            name='SearchKeyword',
        ),
    ]
