# Generated by Django 4.0.2 on 2024-08-18 16:53

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_searchhistory_alter_searchkeyword_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
            migrations.RunSQL(
            sql="CREATE INDEX searchhistory_search_vector_idx ON search_searchhistory USING GIN (search_vector);",
            reverse_sql="DROP INDEX searchhistory_search_vector_idx;",
        ),
    ]
