# Generated by Django 4.0.2 on 2024-08-18 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_searchhistory_search_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='search_vector',
        ),
    ]
