# Generated by Django 4.0.2 on 2024-08-18 21:36

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_remove_searchhistory_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
