# Generated by Django 4.0.2 on 2024-08-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_remove_searchhistory_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keyword_search_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='search_query_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
