# Generated by Django 4.0.2 on 2024-07-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_users_alter_chatroom_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='users',
        ),
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
