# Generated by Django 4.0.2 on 2024-07-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chatroom_description_chatroom_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='chat_type',
            field=models.CharField(choices=[('1to1', '1-to-1'), ('group', 'Group')], default='group', max_length=10),
        ),
    ]
