# Generated by Django 4.0.2 on 2024-07-25 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_follow_followed_alter_follow_follower'),
        ('chat', '0006_rename_message_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='users',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.profile'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='profiles',
            field=models.ManyToManyField(blank=True, to='users.Profile'),
        ),
    ]
