# Generated by Django 4.0.2 on 2025-02-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_chatmessage_user_remove_chatroom_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='timestamp',
            new_name='created_on',
        ),
    ]
