# Generated by Django 4.0.2 on 2025-02-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_log_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='status',
        ),
    ]
