# Generated by Django 4.0.2 on 2024-07-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_reply_comment_replies_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='object_id',
        ),
        migrations.AddField(
            model_name='blog',
            name='comments',
            field=models.ManyToManyField(to='posts.Comment'),
        ),
        migrations.AddField(
            model_name='comic',
            name='comments',
            field=models.ManyToManyField(to='posts.Comment'),
        ),
        migrations.AddField(
            model_name='novel',
            name='comments',
            field=models.ManyToManyField(to='posts.Comment'),
        ),
        migrations.AddField(
            model_name='poll',
            name='comments',
            field=models.ManyToManyField(to='posts.Comment'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='comments',
            field=models.ManyToManyField(to='posts.Comment'),
        ),
    ]
