# Generated by Django 4.0.2 on 2024-07-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_created_at_blog_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
