# Generated by Django 4.0.2 on 2024-07-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_follow_followed_alter_follow_follower'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('posts', '0004_bookmark_created_on'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookmark',
            new_name='PostBookmark',
        ),
    ]
