# Generated by Django 4.0.2 on 2024-07-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_comment_content_type_remove_comment_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='comments',
            field=models.ManyToManyField(blank=True, to='posts.Comment'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='comments',
            field=models.ManyToManyField(blank=True, to='posts.Comment'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='comments',
            field=models.ManyToManyField(blank=True, to='posts.Comment'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='comments',
            field=models.ManyToManyField(blank=True, to='posts.Comment'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='comments',
            field=models.ManyToManyField(blank=True, to='posts.Comment'),
        ),
    ]
