# Generated by Django 4.0.2 on 2024-07-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_follow_followed_alter_follow_follower'),
        ('posts', '0006_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(to='users.Profile'),
        ),
        migrations.AddField(
            model_name='comic',
            name='likes',
            field=models.ManyToManyField(to='users.Profile'),
        ),
        migrations.AddField(
            model_name='novel',
            name='likes',
            field=models.ManyToManyField(to='users.Profile'),
        ),
        migrations.AddField(
            model_name='poll',
            name='likes',
            field=models.ManyToManyField(to='users.Profile'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='likes',
            field=models.ManyToManyField(to='users.Profile'),
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
