# Generated by Django 4.0.2 on 2024-07-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_blog_likes_comic_likes_novel_likes_poll_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='hashtags_blogs', to='posts.Hashtag'),
        ),
    ]
