# Generated by Django 4.0.2 on 2024-07-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_blog_comments_alter_comic_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='comments',
        ),
    ]
