# Generated by Django 4.0.2 on 2024-07-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_blog_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='media',
            field=models.ImageField(blank=True, default='no_img.png', null=True, upload_to='blog_cover/'),
        ),
        migrations.AddField(
            model_name='quizchoice',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_icons/'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='media',
            field=models.ImageField(default='no_img.png', upload_to='comic_cover/'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='media',
            field=models.ImageField(default='no_img.png', upload_to='novel_cover/'),
        ),
    ]
