# Generated by Django 4.0.2 on 2024-07-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_blog_comments_comic_comments_novel_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comments',
        ),
        migrations.AddField(
            model_name='blog',
            name='comments',
            field=models.ManyToManyField(blank=True, to='posts.Comment'),
        ),
        migrations.RemoveField(
            model_name='comic',
            name='comments',
        ),
        migrations.AddField(
            model_name='comic',
            name='comments',
            field=models.ManyToManyField(blank=True, to='posts.Comment'),
        ),
        migrations.RemoveField(
            model_name='novel',
            name='comments',
        ),
        migrations.AddField(
            model_name='novel',
            name='comments',
            field=models.ManyToManyField(blank=True, to='posts.Comment'),
        ),
        migrations.RemoveField(
            model_name='poll',
            name='comments',
        ),
        migrations.AddField(
            model_name='poll',
            name='comments',
            field=models.ManyToManyField(blank=True, to='posts.Comment'),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='comments',
        ),
        migrations.AddField(
            model_name='quiz',
            name='comments',
            field=models.ManyToManyField(blank=True, to='posts.Comment'),
        ),
    ]
