# Generated by Django 4.0.2 on 2024-08-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_blog_likes_alter_comic_likes_alter_novel_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='blog_cover/'),
        ),
    ]
