# Generated by Django 4.0.2 on 2024-08-08 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alliances', '0004_alliancelevel_c_requirement_alliancestats_level'),
        ('posts', '0011_alter_blog_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='alliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alliances.alliance'),
        ),
        migrations.AddField(
            model_name='comic',
            name='alliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alliances.alliance'),
        ),
        migrations.AddField(
            model_name='novel',
            name='alliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alliances.alliance'),
        ),
        migrations.AddField(
            model_name='poll',
            name='alliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alliances.alliance'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='alliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alliances.alliance'),
        ),
    ]
