# Generated by Django 4.0.2 on 2024-08-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_quizchoice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizchoice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
