# Generated by Django 4.0.2 on 2024-08-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_remove_blog_hashtags_remove_novel_hashtags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLIC', 'Public'), ('PRIVATE', 'Private')], db_index=True, default='PUBLIC', max_length=7),
        ),
        migrations.AlterField(
            model_name='comic',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLIC', 'Public'), ('PRIVATE', 'Private')], db_index=True, default='PUBLIC', max_length=7),
        ),
        migrations.AlterField(
            model_name='novel',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLIC', 'Public'), ('PRIVATE', 'Private')], db_index=True, default='PUBLIC', max_length=7),
        ),
        migrations.AlterField(
            model_name='poll',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLIC', 'Public'), ('PRIVATE', 'Private')], db_index=True, default='PUBLIC', max_length=7),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLIC', 'Public'), ('PRIVATE', 'Private')], db_index=True, default='PUBLIC', max_length=7),
        ),
    ]
