# Generated by Django 4.0.2 on 2024-08-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_follow_followed_alter_follow_follower'),
        ('posts', '0016_blog_likes_count_comic_likes_count_novel_likes_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollchoice',
            name='votes',
        ),
        migrations.AddField(
            model_name='pollchoice',
            name='votes',
            field=models.ManyToManyField(blank=True, null=True, to='users.Profile'),
        ),
    ]
