# Generated by Django 4.0.2 on 2024-08-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_follow_followed_alter_follow_follower'),
        ('posts', '0017_remove_pollchoice_votes_pollchoice_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollchoice',
            name='votes',
            field=models.ManyToManyField(blank=True, to='users.Profile'),
        ),
    ]
