# Generated by Django 4.0.2 on 2024-09-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_alter_keyword_keyword_search_count_and_more'),
        ('posts', '0018_alter_pollchoice_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='keywords_score',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='comic',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='search.Keyword'),
        ),
        migrations.AddField(
            model_name='comic',
            name='keywords_score',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='novel',
            name='keywords_score',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='search.Keyword'),
        ),
        migrations.AddField(
            model_name='poll',
            name='keywords_score',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='search.Keyword'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='keywords_score',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='search.Keyword'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='search.Keyword'),
        ),
    ]
