# Generated by Django 4.0.2 on 2024-09-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_follow_followed_alter_follow_follower'),
        ('posts', '0019_blog_keywords_score_comic_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='clicks',
            field=models.ManyToManyField(related_name='+', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='comic',
            name='clicks',
            field=models.ManyToManyField(related_name='+', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='novel',
            name='clicks',
            field=models.ManyToManyField(related_name='+', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='poll',
            name='clicks',
            field=models.ManyToManyField(related_name='+', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='clicks',
            field=models.ManyToManyField(related_name='+', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='+', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='+', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='+', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='+', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='+', to='users.Profile'),
        ),
    ]
