# Generated by Django 4.0.2 on 2024-09-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_blog_clicks_comic_clicks_novel_clicks_poll_clicks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='clicks_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='comic',
            name='clicks_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='novel',
            name='clicks_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='clicks_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='clicks_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
