# Generated by Django 4.0.2 on 2024-09-05 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0002_alter_follow_followed_alter_follow_follower'),
        ('posts', '0021_blog_clicks_count_comic_clicks_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='clicks',
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['content_type', 'object_id'], name='posts_click_content_e70f8f_idx'),
        ),
    ]
