# Generated by Django 4.0.2 on 2024-09-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_remove_blog_clicks_remove_comic_clicks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='keywords_score',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='likes_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='comic',
            name='keywords_score',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='likes_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='novel',
            name='keywords_score',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='novel',
            name='likes_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='keywords_score',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='likes_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='keywords_score',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='likes_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
