# Generated by Django 4.0.2 on 2025-02-25 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alliances', '0006_alter_alliancemember_unique_together'),
        ('posts', '0024_alter_blog_description_alter_blog_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='alliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alliances.alliance'),
        ),
    ]
