# Generated by Django 4.0.2 on 2025-02-26 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alliances', '0006_alter_alliancemember_unique_together'),
        ('posts', '0025_blog_alliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='alliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alliances.alliance'),
        ),
        migrations.AddField(
            model_name='novel',
            name='alliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alliances.alliance'),
        ),
        migrations.AddField(
            model_name='poll',
            name='alliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alliances.alliance'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='alliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alliances.alliance'),
        ),
    ]
