# Generated by Django 4.0.2 on 2025-02-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
