# Generated by Django 4.0.2 on 2024-07-10 10:54

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_follow_followed_alter_follow_follower'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(default='alliance.png', upload_to='alliance_icons/')),
                ('description', models.TextField(max_length=1024)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('communities', models.ManyToManyField(to='communities.Community')),
            ],
        ),
        migrations.CreateModel(
            name='AllianceBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='alliance_badges/')),
                ('description', models.TextField(max_length=1024)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllianceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', django_quill.fields.QuillField()),
                ('media', models.ImageField(upload_to='alliance_event_media/')),
            ],
        ),
        migrations.CreateModel(
            name='AllianceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_power', models.FloatField(default=0)),
                ('popularity_points', models.FloatField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('comm_count', models.IntegerField(default=1)),
                ('alliance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='alliances.alliance')),
            ],
        ),
        migrations.CreateModel(
            name='AllianceMissionRewardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='AllianceMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1024)),
                ('c_reward', models.FloatField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('DAILY', 'daily'), ('WEEKLY', 'weekly'), ('MONTHLY', 'monthly')], default='DAILY', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('reward', models.ManyToManyField(blank=True, to='alliances.AllianceMissionRewardItem')),
            ],
        ),
        migrations.CreateModel(
            name='AllianceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('acquired_on', models.DateTimeField(auto_now_add=True)),
                ('badge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alliances.alliancebadge')),
            ],
        ),
        migrations.CreateModel(
            name='AllianceEventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='alliance_event_media/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='alliances.allianceevent')),
            ],
        ),
        migrations.CreateModel(
            name='AllianceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MEMBER', 'member'), ('OWNER', 'owner'), ('MODERATOR', 'moderator')], default='member', max_length=20)),
                ('power', models.FloatField(default=0.0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('alliance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alliances.alliance')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'unique_together': {('alliance', 'profile')},
            },
        ),
    ]
