# Generated by Django 4.0.2 on 2024-07-03 16:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='alliance_icons/')),
                ('description', models.CharField(max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
