# Generated by Django 4.0.2 on 2024-07-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliance',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
