# Generated by Django 4.0.2 on 2024-07-03 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alliances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliance',
            name='description',
            field=models.CharField(max_length=1024),
        ),
        migrations.CreateModel(
            name='AllianceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_power', models.FloatField(default=0)),
                ('popularity_points', models.FloatField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='alliances.alliance')),
            ],
        ),
    ]
