# Generated by Django 4.0.2 on 2024-07-04 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alliances', '0002_alter_alliance_description_alliancestats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliancestats',
            name='alliance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='alliances.alliance'),
        ),
    ]
