# Generated by Django 4.0.2 on 2024-07-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alliances', '0002_alliance_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllianceEventMedia',
        ),
    ]
