# Generated by Django 4.0.2 on 2024-07-04 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('alliances', '0003_alter_alliancestats_alliance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllianceBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='alliance_badges/')),
                ('description', models.CharField(max_length=1024)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllianceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('acquired_on', models.DateTimeField()),
                ('badge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alliances.alliancebadge')),
            ],
        ),
        migrations.CreateModel(
            name='AllianceCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alliances.alliance')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.community')),
            ],
        ),
    ]
