# Generated by Django 4.0.2 on 2024-07-21 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alliances', '0003_delete_allianceeventmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliancelevel',
            name='c_requirement',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='alliancestats',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alliances.alliancelevel'),
        ),
    ]
