# Generated by Django 4.0.2 on 2024-08-13 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_follow_followed_alter_follow_follower'),
        ('alliances', '0004_alliancelevel_c_requirement_alliancestats_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliancemember',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
