# Generated by Django 4.0.2 on 2024-07-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('alliances', '0004_alliancebadge_alliancelevel_alliancecommunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllianceMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1024)),
                ('c_reward', models.FloatField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='alliancecommunity',
            unique_together={('alliance', 'community')},
        ),
    ]
