# Generated by Django 4.0.2 on 2024-08-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alliances', '0005_alter_alliancemember_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alliancemember',
            unique_together=set(),
        ),
    ]
