# Generated by Django 4.0.2 on 2024-07-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('alliances', '0006_allianceevent_alter_alliance_icon_allianceeventmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliancebadge',
            name='communities',
            field=models.ManyToManyField(blank=True, null=True, to='communities.Community'),
        ),
        migrations.DeleteModel(
            name='AllianceCommunity',
        ),
    ]
