# Generated by Django 4.0.2 on 2024-07-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('alliances', '0007_alliancebadge_communities_delete_alliancecommunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliancebadge',
            name='communities',
            field=models.ManyToManyField(blank=True, to='communities.Community'),
        ),
    ]
