# Generated by Django 4.0.2 on 2024-07-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliances', '0010_alliancestats_comm_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliancemission',
            name='type',
            field=models.CharField(choices=[('DAILY', 'daily'), ('WEEKLY', 'weekly'), ('MONTHLY', 'monthly')], default='DAILY', max_length=20),
        ),
        migrations.AlterField(
            model_name='alliancemission',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
