# Generated by Django 4.0.2 on 2024-07-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliances', '0011_alliancemission_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliance',
            name='icon',
            field=models.ImageField(default='alliance.png', upload_to='alliance_icons/'),
        ),
    ]
