# Generated by Django 4.0.2 on 2024-07-09 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('users', '0002_alter_follow_followed_alter_follow_follower'),
        ('alliances', '0013_alter_alliance_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllianceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(choices=[('MEMBER', 'member'), ('OWNER', 'owner'), ('MODERATOR', 'moderator')], default='member', max_length=20)),
                ('power', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name='alliance',
            name='communities',
            field=models.ManyToManyField(to='communities.Community'),
        ),
        migrations.DeleteModel(
            name='AllianceContribution',
        ),
        migrations.AddField(
            model_name='alliancemember',
            name='alliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alliances.alliance'),
        ),
        migrations.AddField(
            model_name='alliancemember',
            name='contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
