# Generated by Django 4.0.2 on 2024-07-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alliances', '0014_alliancemember_alter_alliance_communities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alliancemember',
            old_name='contributor',
            new_name='profile',
        ),
    ]
