# Generated by Django 4.0.2 on 2024-07-09 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alliances', '0015_rename_contributor_alliancemember_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alliancemember',
            old_name='roles',
            new_name='role',
        ),
    ]
