# Generated by Django 4.0.2 on 2024-08-09 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alliances', '0004_alliancelevel_c_requirement_alliancestats_level'),
        ('users', '0002_alter_follow_followed_alter_follow_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alliances.alliance'),
        ),
    ]
